#!/bin/bash

    
if [[ ! -f "/var/www/haproxy-wi/app/certs/haproxy-wi.key" ]]
then
	openssl req -newkey rsa:4096 -nodes \
    		-keyout /var/www/haproxy-wi/app/certs/haproxy-wi.key -x509 -days 10365 \
    		-out /var/www/haproxy-wi/app/certs/haproxy-wi.crt \
	  	-subj "/C=US/ST=Almaty/L=Springfield/O=Roxy-WI/OU=IT/CN=*.example.com/emailAddress=haproxy-wi@example.com" 
fi

if [[ ! -f "/help/supervisor_secure" ]]
then
	/bin/bash /help/supervisor_secrets.sh
fi
echo $(which python)
echo $(which supervisord)
exec python3 supervisord -c /etc/supervisor/supervisord.conf
