name: Dev Workflow

on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Push_Docker Dev
        uses: docker/build-push-action@v3
        with:
          file: dev.Dockerfile
          push: true
          tags: yanik39/haproxy-wi:dev
